<?php

use Illuminate\Database\Seeder;

class TownTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        \Illuminate\Support\Facades\DB::table('towns')->truncate();

        $towns = [
            ["city_id" => 1,"name" => "A&C Mall"],
            ["city_id" => 1,"name" => "Abeka"],
            ["city_id" => 1,"name" => "Abelemkpe"],
            ["city_id" => 1,"name" => "Abokobi"],
            ["city_id" => 1,"name" => "Abossey Okai"],
            ["city_id" => 1,"name" => "Accra Mall"],
            ["city_id" => 1,"name" => "Accra New Town"],
            ["city_id" => 1,"name" => "Achimota"],
            ["city_id" => 1,"name" => "Achimota Retail Centre"],
            ["city_id" => 1,"name" => "Ada"],
            ["city_id" => 1,"name" => "Adabraka"],
            ["city_id" => 1,"name" => "Adenta"],
            ["city_id" => 1,"name" => "Adjiringanor"],
            ["city_id" => 1,"name" => "Agbogbloshie market"],
            ["city_id" => 1,"name" => "Airport City"],
            ["city_id" => 1,"name" => "Airport Hills"],
            ["city_id" => 1,"name" => "Airport Residential Area"],
            ["city_id" => 1,"name" => "Akweteyman"],
            ["city_id" => 1,"name" => "Alajo"],
            ["city_id" => 1,"name" => "Amasaman"],
            ["city_id" => 1,"name" => "Amomole"],
            ["city_id" => 1,"name" => "Apenkwa"],
            ["city_id" => 1,"name" => "Ashaima"],
            ["city_id" => 1,"name" => "Asylum Down"],
            ["city_id" => 1,"name" => "Avenor"],
            ["city_id" => 1,"name" => "Aviance"],
            ["city_id" => 1,"name" => "Awoshie"],
            ["city_id" => 1,"name" => "Awudome"],
            ["city_id" => 1,"name" => "Bawaleshie"],
            ["city_id" => 1,"name" => "Black Star Square"],
            ["city_id" => 1,"name" => "Bubuashie"],
            ["city_id" => 1,"name" => "Burma Camp"],
            ["city_id" => 1,"name" => "Cantonments"],
            ["city_id" => 1,"name" => "Caprice"],
            ["city_id" => 1,"name" => "Central Business District"],
            ["city_id" => 1,"name" => "Chorkor"],
            ["city_id" => 1,"name" => "Christian Village"],
            ["city_id" => 1,"name" => "Circle"],
            ["city_id" => 1,"name" => "Dansoman"],
            ["city_id" => 1,"name" => "Darkuman"],
            ["city_id" => 1,"name" => "Dodowa"],
            ["city_id" => 1,"name" => "Dome"],
            ["city_id" => 1,"name" => "Dzorwulu"],
            ["city_id" => 1,"name" => "East Airport"],
            ["city_id" => 1,"name" => "East Cantonments"],
            ["city_id" => 1,"name" => "East Darkuman"],
            ["city_id" => 1,"name" => "East Legon"],
            ["city_id" => 1,"name" => "East Legon Hills"],
            ["city_id" => 1,"name" => "El Wak Stadium"],
            ["city_id" => 1,"name" => "Gbebu"],
            ["city_id" => 1,"name" => "Haatso"],
            ["city_id" => 1,"name" => "High Street"],
            ["city_id" => 1,"name" => "Jamestown"],
            ["city_id" => 1,"name" => "Junction Mall"],
            ["city_id" => 1,"name" => "Kanda"],
            ["city_id" => 1,"name" => "Kaneshie"],
            ["city_id" => 1,"name" => "Kaneshie Market"],
            ["city_id" => 1,"name" => "Kantamanto Market"],
            ["city_id" => 1,"name" => "Kawukudi"],
            ["city_id" => 1,"name" => "Kinka"],
            ["city_id" => 1,"name" => "Kinkawe"],
            ["city_id" => 1,"name" => "Kisseman"],
            ["city_id" => 1,"name" => "Kokomlemle"],
            ["city_id" => 1,"name" => "Korle Bu"],
            ["city_id" => 1,"name" => "Korle Dudor"],
            ["city_id" => 1,"name" => "Korle Gorno"],
            ["city_id" => 1,"name" => "Korle Wonkon"],
            ["city_id" => 1,"name" => "Kotobabi"],
            ["city_id" => 1,"name" => "Kotoka Airport"],
            ["city_id" => 1,"name" => "Kwabenya"],
            ["city_id" => 1,"name" => "Kwashieman"],
            ["city_id" => 1,"name" => "La "],
            ["city_id" => 1,"name" => "Labadi"],
            ["city_id" => 1,"name" => "Labone"],
            ["city_id" => 1,"name" => "Lapaz"],
            ["city_id" => 1,"name" => "Lartebiokorshie"],
            ["city_id" => 1,"name" => "Maamobi"],
            ["city_id" => 1,"name" => "Madina"],
            ["city_id" => 1,"name" => "Makola Market"],
            ["city_id" => 1,"name" => "Mallam"],
            ["city_id" => 1,"name" => "Mamprobi"],
            ["city_id" => 1,"name" => "Manet"],
            ["city_id" => 1,"name" => "Marina Mall"],
            ["city_id" => 1,"name" => "Marina Mall"],
            ["city_id" => 1,"name" => "Mataheko"],
            ["city_id" => 1,"name" => "Mataheko"],
            ["city_id" => 1,"name" => "McCarthy Hill"],
            ["city_id" => 1,"name" => "Ministires"],
            ["city_id" => 1,"name" => "Mpoase"],
            ["city_id" => 1,"name" => "New Mamprobi"],
            ["city_id" => 1,"name" => "Ngleshie"],
            ["city_id" => 1,"name" => "Ngleshie Amanfro"],
            ["city_id" => 1,"name" => "Nii Boi Town"],
            ["city_id" => 1,"name" => "Nii Boiman"],
            ["city_id" => 1,"name" => "Nima East"],
            ["city_id" => 1,"name" => "Nima West"],
            ["city_id" => 1,"name" => "North Adabraka"],
            ["city_id" => 1,"name" => "North Industrial Area"],
            ["city_id" => 1,"name" => "North Kaneshie"],
            ["city_id" => 1,"name" => "North Ridge"],
            ["city_id" => 1,"name" => "Nungua"],
            ["city_id" => 1,"name" => "Odorkor"],
            ["city_id" => 1,"name" => "Okaishie"],
            ["city_id" => 1,"name" => "Osu"],
            ["city_id" => 1,"name" => "Osu Doku"],
            ["city_id" => 1,"name" => "Osu RE"],
            ["city_id" => 1,"name" => "Oxford Street Mall"],
            ["city_id" => 1,"name" => "Oyarefa"],
            ["city_id" => 1,"name" => "Pig Farm"],
            ["city_id" => 1,"name" => "Pokuase"],
            ["city_id" => 1,"name" => "Prampram"],
            ["city_id" => 1,"name" => "Rawlings Park"],
            ["city_id" => 1,"name" => "Regimanuel Estates"],
            ["city_id" => 1,"name" => "Ridge"],
            ["city_id" => 1,"name" => "Ring Road"],
            ["city_id" => 1,"name" => "Ringway Estates"],
            ["city_id" => 1,"name" => "Roman Ridge"],
            ["city_id" => 1,"name" => "Sakaman"],
            ["city_id" => 1,"name" => "Shiabu"],
            ["city_id" => 1,"name" => "Shiashie"],
            ["city_id" => 1,"name" => "Sowutuom"],
            ["city_id" => 1,"name" => "Spintex Road"],
            ["city_id" => 1,"name" => "Tesano"],
            ["city_id" => 1,"name" => "Teshie"],
            ["city_id" => 1,"name" => "Trade Fair"],
            ["city_id" => 1,"name" => "Tudu"],
            ["city_id" => 1,"name" => "Villagio"],
            ["city_id" => 1,"name" => "Weija"],
            ["city_id" => 1,"name" => "West Hills Mall"],
            ["city_id" => 1,"name" => "West Legon/ Westlands"],
            ["city_id" => 1,"name" => "Wuoyeman"],
            ["city_id" => 2,"name" => "Aboabo"],
            ["city_id" => 2,"name" => "Abrepo"],
            ["city_id" => 2,"name" => "Abrepo Junction"],
            ["city_id" => 2,"name" => "Abusuakruwa"],
            ["city_id" => 2,"name" => "Adiebeba"],
            ["city_id" => 2,"name" => "Adiembra"],
            ["city_id" => 2,"name" => "Adoato"],
            ["city_id" => 2,"name" => "Adum"],
            ["city_id" => 2,"name" => "Afful Nkwanta"],
            ["city_id" => 2,"name" => "Afia Kobi"],
            ["city_id" => 2,"name" => "Agric"],
            ["city_id" => 2,"name" => "Ahenbronum"],
            ["city_id" => 2,"name" => "Ahenma Kokoben"],
            ["city_id" => 2,"name" => "Ahinsan"],
            ["city_id" => 2,"name" => "Ahinsan Estate"],
            ["city_id" => 2,"name" => "Ahodwo"],
            ["city_id" => 2,"name" => "Airport"],
            ["city_id" => 2,"name" => "Akwatia Line"],
            ["city_id" => 2,"name" => "Alabaa"],
            ["city_id" => 2,"name" => "Amakom"],
            ["city_id" => 2,"name" => "Anlo Fante New Town"],
            ["city_id" => 2,"name" => "Anloga Junction"],
            ["city_id" => 2,"name" => "Anomangye"],
            ["city_id" => 2,"name" => "Apatrapa"],
            ["city_id" => 2,"name" => "Aprabo"],
            ["city_id" => 2,"name" => "Apraman"],
            ["city_id" => 2,"name" => "Asafo"],
            ["city_id" => 2,"name" => "Asafo Market"],
            ["city_id" => 2,"name" => "Asawasi"],
            ["city_id" => 2,"name" => "Asem"],
            ["city_id" => 2,"name" => "Asokore Mampong"],
            ["city_id" => 2,"name" => "Asokwa"],
            ["city_id" => 2,"name" => "Asuyeboa"],
            ["city_id" => 2,"name" => "Atasomanso"],
            ["city_id" => 2,"name" => "Atonsu"],
            ["city_id" => 2,"name" => "Ayeduase"],
            ["city_id" => 2,"name" => "Ayidyase"],
            ["city_id" => 2,"name" => "Bantama"],
            ["city_id" => 2,"name" => "Bantama Market"],
            ["city_id" => 2,"name" => "Bekwai"],
            ["city_id" => 2,"name" => "Boadi"],
            ["city_id" => 2,"name" => "Bohyen"],
            ["city_id" => 2,"name" => "Bompata"],
            ["city_id" => 2,"name" => "Breman"],
            ["city_id" => 2,"name" => "Buokrom"],
            ["city_id" => 2,"name" => "Buokrom Estate"],
            ["city_id" => 2,"name" => "China Mall"],
            ["city_id" => 2,"name" => "Chirapatre"],
            ["city_id" => 2,"name" => "Daban"],
            ["city_id" => 2,"name" => "Dadiesoaba"],
            ["city_id" => 2,"name" => "Dakodwom"],
            ["city_id" => 2,"name" => "Deduako"],
            ["city_id" => 2,"name" => "Denyame"],
            ["city_id" => 2,"name" => "Dichemso"],
            ["city_id" => 2,"name" => "Dompease"],
            ["city_id" => 2,"name" => "Edwenase"],
            ["city_id" => 2,"name" => "Emena"],
            ["city_id" => 2,"name" => "Ejisu"],
            ["city_id" => 2,"name" => "Fankyenebra"],
            ["city_id" => 2,"name" => "Fante New Town"],
            ["city_id" => 2,"name" => "Gyinase"],
            ["city_id" => 2,"name" => "Kaase"],
            ["city_id" => 2,"name" => "Kajetia Market"],
            ["city_id" => 2,"name" => "Kentinkrono"],
            ["city_id" => 2,"name" => "KO"],
            ["city_id" => 2,"name" => "Kokoso – Asubonteng"],
            ["city_id" => 2,"name" => "Kotei"],
            ["city_id" => 2,"name" => "Krobo"],
            ["city_id" => 2,"name" => "Krofrom "],
            ["city_id" => 2,"name" => "Kronum"],
            ["city_id" => 2,"name" => "Kumasi City Mall"],
            ["city_id" => 2,"name" => "Kuwait"],
            ["city_id" => 2,"name" => "Kwadaso"],
            ["city_id" => 2,"name" => "Kwadaso Estate"],
            ["city_id" => 2,"name" => "Kwapra"],
            ["city_id" => 2,"name" => "Maakro"],
            ["city_id" => 2,"name" => "Manhyia"],
            ["city_id" => 2,"name" => "Moshe Zongo"],
            ["city_id" => 2,"name" => "New Zongo"],
            ["city_id" => 2,"name" => "Nhyiaeso"],
            ["city_id" => 2,"name" => "North Suntreso"],
            ["city_id" => 2,"name" => "Nsiah Asare"],
            ["city_id" => 2,"name" => "Nsuoase"],
            ["city_id" => 2,"name" => "Nzima"],
            ["city_id" => 2,"name" => "Odeneho Kwadaso"],
            ["city_id" => 2,"name" => "Odumasi"],
            ["city_id" => 2,"name" => "Oduom"],
            ["city_id" => 2,"name" => "Oforikrom"],
            ["city_id" => 2,"name" => "Ohwim – Amanfrom"],
            ["city_id" => 2,"name" => "Ohwimase – Denkyemuoso"],
            ["city_id" => 2,"name" => "Old Tafo"],
            ["city_id" => 2,"name" => "Pankrono"],
            ["city_id" => 2,"name" => "Pankrono East"],
            ["city_id" => 2,"name" => "Paraku Estate"],
            ["city_id" => 2,"name" => "Patase"],
            ["city_id" => 2,"name" => "Patase Estate"],
            ["city_id" => 2,"name" => "Ridge Nhyiaeso"],
            ["city_id" => 2,"name" => "Roman Hill"],
            ["city_id" => 2,"name" => "Santase"],
            ["city_id" => 2,"name" => "Sepe"],
            ["city_id" => 2,"name" => "Sokoban"],
            ["city_id" => 2,"name" => "South Suntreso"],
            ["city_id" => 2,"name" => "Stadium"],
            ["city_id" => 2,"name" => "Suame"],
            ["city_id" => 2,"name" => "Suame Magazine"],
            ["city_id" => 2,"name" => "Subin"],
            ["city_id" => 2,"name" => "Tafo"],
            ["city_id" => 2,"name" => "Tafo Nhyiaeso"],
            ["city_id" => 2,"name" => "Tafo Pankrono Estate"],
            ["city_id" => 2,"name" => "Tanoso"],
            ["city_id" => 2,"name" => "Tarkwa-Maakro"],
            ["city_id" => 2,"name" => "Tech"],
            ["city_id" => 2,"name" => "Yenyawoso"],
            ["city_id" => 3,"name" => "Community 1"],
            ["city_id" => 3,"name" => "Community 1 Central Business District"],
            ["city_id" => 3,"name" => "Community 2"],
            ["city_id" => 3,"name" => "Community 3"],
            ["city_id" => 3,"name" => "Community 4"],
            ["city_id" => 3,"name" => "Community 5"],
            ["city_id" => 3,"name" => "Community 6"],
            ["city_id" => 3,"name" => "Community 7"],
            ["city_id" => 3,"name" => "Community 8"],
            ["city_id" => 3,"name" => "Community 9"],
            ["city_id" => 3,"name" => "Community 10"],
            ["city_id" => 3,"name" => "Community 11"],
            ["city_id" => 3,"name" => "Community 12"],
            ["city_id" => 3,"name" => "Community 13"],
            ["city_id" => 3,"name" => "Community 14"],
            ["city_id" => 3,"name" => "Community 15"],
            ["city_id" => 3,"name" => "Community 16"],
            ["city_id" => 3,"name" => "Community 17"],
            ["city_id" => 3,"name" => "Community 18"],
            ["city_id" => 3,"name" => "Community 19"],
            ["city_id" => 3,"name" => "Community 20"],
            ["city_id" => 3,"name" => "Community 21"],
            ["city_id" => 3,"name" => "Community 22"],
            ["city_id" => 3,"name" => "Community 23"],
            ["city_id" => 3,"name" => "Community 24"],
            ["city_id" => 3,"name" => "Community 25"],
            ["city_id" => 3,"name" => "Community 26"],
            ["city_id" => 3,"name" => "Fishing Harbour"],
            ["city_id" => 3,"name" => "Free Zones Enclave"],
            ["city_id" => 3,"name" => "Industrial Area"],
            ["city_id" => 3,"name" => "Kpone"],
            ["city_id" => 3,"name" => "Sakumono"],
            ["city_id" => 3,"name" => "Tema Central Mall"],
            ["city_id" => 3,"name" => "Tema General Hospital Area"],
            ["city_id" => 3,"name" => "Tema Harbour"],
            ["city_id" => 4,"name" => "Aboadze"],
            ["city_id" => 4,"name" => "Adiembra"],
            ["city_id" => 4,"name" => "Adientem"],
            ["city_id" => 4,"name" => "Ahinkofikrom"],
            ["city_id" => 4,"name" => "Airforce Station"],
            ["city_id" => 4,"name" => "Airport Ridge"],
            ["city_id" => 4,"name" => "Amanful"],
            ["city_id" => 4,"name" => "Anagye"],
            ["city_id" => 4,"name" => "Anoe"],
            ["city_id" => 4,"name" => "Apollo"],
            ["city_id" => 4,"name" => "Apremdo"],
            ["city_id" => 4,"name" => "Asafo"],
            ["city_id" => 4,"name" => "Asamang"],
            ["city_id" => 4,"name" => "Asamansudu"],
            ["city_id" => 4,"name" => "Assakae"],
            ["city_id" => 4,"name" => "Axim Road"],
            ["city_id" => 4,"name" => "Bakakyir"],
            ["city_id" => 4,"name" => "Bankyease"],
            ["city_id" => 4,"name" => "Beach Road"],
            ["city_id" => 4,"name" => "Buabakrom"],
            ["city_id" => 4,"name" => "Butumagyebu"],
            ["city_id" => 4,"name" => "Cassava Farm"],
            ["city_id" => 4,"name" => "Central Business District"],
            ["city_id" => 4,"name" => "Chapel Hill"],
            ["city_id" => 4,"name" => "Cocoa Villa"],
            ["city_id" => 4,"name" => "Dixcove Hill"],
            ["city_id" => 4,"name" => "East Tanokrom"],
            ["city_id" => 4,"name" => "Effia"],
            ["city_id" => 4,"name" => "EffiaKuma East"],
            ["city_id" => 4,"name" => "EffiaKuma West"],
            ["city_id" => 4,"name" => "EffiaKuma Zongo"],
            ["city_id" => 4,"name" => "Effie-Nkwanta"],
            ["city_id" => 4,"name" => "Ekuasi"],
            ["city_id" => 4,"name" => "Esikado"],
            ["city_id" => 4,"name" => "Esikafoabentem. No. 1"],
            ["city_id" => 4,"name" => "Esikafoabentem. No. 3"],
            ["city_id" => 4,"name" => "Esikafoambantsem No 2"],
            ["city_id" => 4,"name" => "Essaman"],
            ["city_id" => 4,"name" => "Essipon"],
            ["city_id" => 4,"name" => "Fijai"],
            ["city_id" => 4,"name" => "Funko"],
            ["city_id" => 4,"name" => "GPHA Quaters"],
            ["city_id" => 4,"name" => "Kansaworado"],
            ["city_id" => 4,"name" => "Ketan"],
            ["city_id" => 4,"name" => "Ketan Estates"],
            ["city_id" => 4,"name" => "Kojokrom"],
            ["city_id" => 4,"name" => "Kweikuma"],
            ["city_id" => 4,"name" => "Kwesimintim"],
            ["city_id" => 4,"name" => "Lagos Town"],
            ["city_id" => 4,"name" => "Lower New Takoradi"],
            ["city_id" => 4,"name" => "Mampong"],
            ["city_id" => 4,"name" => "Market Circle"],
            ["city_id" => 4,"name" => "Mempeasem"],
            ["city_id" => 4,"name" => "Mpentemnsrew"],
            ["city_id" => 4,"name" => "Mpintsin"],
            ["city_id" => 4,"name" => "New Takoradi"],
            ["city_id" => 4,"name" => "Nketsiakrom"],
            ["city_id" => 4,"name" => "Nkontompo"],
            ["city_id" => 4,"name" => "Ntangufo"],
            ["city_id" => 4,"name" => "Odumasi"],
            ["city_id" => 4,"name" => "Old Adra"],
            ["city_id" => 4,"name" => "Poasi"],
            ["city_id" => 4,"name" => "Railway Quarters Harbour"],
            ["city_id" => 4,"name" => "Ridge Ministies"],
            ["city_id" => 4,"name" => "Sabon Zongo"],
            ["city_id" => 4,"name" => "Sekondi"],
            ["city_id" => 4,"name" => "Sekondi-Takoradi"],
            ["city_id" => 4,"name" => "Takoradi Airport"],
            ["city_id" => 4,"name" => "Takoradi Harbour"],
            ["city_id" => 4,"name" => "Takoradi Mall"],
            ["city_id" => 4,"name" => "West Tanokrom"],
            ["city_id" => 4,"name" => "Whindo"],
            ["city_id" => 4,"name" => "Windy Ridge"],
            ["city_id" => 4,"name" => "Yensuadu"],
            ["city_id" => 4,"name" => "Zongo Estate"],
            ["city_id" => 5,"name" => "3rd Ridge"],
            ["city_id" => 5,"name" => "Abakam"],
            ["city_id" => 5,"name" => "Aboom Wells"],
            ["city_id" => 5,"name" => "Aboom/Master Sam"],
            ["city_id" => 5,"name" => "Abrofo Mpaono"],
            ["city_id" => 5,"name" => "Abura-Dunkwa"],
            ["city_id" => 5,"name" => "Aburankwanta"],
            ["city_id" => 5,"name" => "Adisadel"],
            ["city_id" => 5,"name" => "Agona Swedru"],
            ["city_id" => 5,"name" => "Agwasi"],
            ["city_id" => 5,"name" => "Aheneboboi"],
            ["city_id" => 5,"name" => "Akatichua"],
            ["city_id" => 5,"name" => "Akong"],
            ["city_id" => 5,"name" => "Akweku"],
            ["city_id" => 5,"name" => "Akyim"],
            ["city_id" => 5,"name" => "Amanful East"],
            ["city_id" => 5,"name" => "Amanful West"],
            ["city_id" => 5,"name" => "Amissano"],
            ["city_id" => 5,"name" => "Amosima"],
            ["city_id" => 5,"name" => "Anafo"],
            ["city_id" => 5,"name" => "Ankaful"],
            ["city_id" => 5,"name" => "Anokyin/Fawohodzi"],
            ["city_id" => 5,"name" => "Antem"],
            ["city_id" => 5,"name" => "Apewosika"],
            ["city_id" => 5,"name" => "Asechanu"],
            ["city_id" => 5,"name" => "Asikafoambantem/Antem"],
            ["city_id" => 5,"name" => "Assim"],
            ["city_id" => 5,"name" => "Assin Fosu"],
            ["city_id" => 5,"name" => "Atrankwa"],
            ["city_id" => 5,"name" => "Ayikoo "],
            ["city_id" => 5,"name" => "Bakaano"],
            ["city_id" => 5,"name" => "Birimso"],
            ["city_id" => 5,"name" => "Black Star"],
            ["city_id" => 5,"name" => "Brofoyedur"],
            ["city_id" => 5,"name" => "Cape Coast Castle"],
            ["city_id" => 5,"name" => "Central Business District"],
            ["city_id" => 5,"name" => "Chapel Square/Victoria Park"],
            ["city_id" => 5,"name" => "Ebubonko"],
            ["city_id" => 5,"name" => "Efutu"],
            ["city_id" => 5,"name" => "Ekon Anaafo"],
            ["city_id" => 5,"name" => "Ekon Etsifi"],
            ["city_id" => 5,"name" => "Elmina"],
            ["city_id" => 5,"name" => "Enyitsiwdo"],
            ["city_id" => 5,"name" => "Essuekyir"],
            ["city_id" => 5,"name" => "Etsifi"],
            ["city_id" => 5,"name" => "Eyifua"],
            ["city_id" => 5,"name" => "First Ridge"],
            ["city_id" => 5,"name" => "Gegem"],
            ["city_id" => 5,"name" => "Gyegyeano"],
            ["city_id" => 5,"name" => "Iture"],
            ["city_id" => 5,"name" => "Kadadwen"],
            ["city_id" => 5,"name" => "Kakomddo"],
            ["city_id" => 5,"name" => "Kakum National Park"],
            ["city_id" => 5,"name" => "Kawanopado"],
            ["city_id" => 5,"name" => "Koforidua"],
            ["city_id" => 5,"name" => "Kotokuraba Market."],
            ["city_id" => 5,"name" => "Kroo Town"],
            ["city_id" => 5,"name" => "Kwansimakrom"],
            ["city_id" => 5,"name" => "Kwapro"],
            ["city_id" => 5,"name" => "London Bridge"],
            ["city_id" => 5,"name" => "Mampong"],
            ["city_id" => 5,"name" => "Mpeasem"],
            ["city_id" => 5,"name" => "Mpeasem/Amoakofoa"],
            ["city_id" => 5,"name" => "Nkafoa"],
            ["city_id" => 5,"name" => "Nkwantado"],
            ["city_id" => 5,"name" => "Ntsin"],
            ["city_id" => 5,"name" => "Nyinasin"],
            ["city_id" => 5,"name" => "O L A Low Cost"],
            ["city_id" => 5,"name" => "O L A Madina"],
            ["city_id" => 5,"name" => "Ola"],
            ["city_id" => 5,"name" => "Pedu Abakadze"],
            ["city_id" => 5,"name" => "Pedu Nguabado"],
            ["city_id" => 5,"name" => "Tamesease"],
            ["city_id" => 5,"name" => "Tantri"],
            ["city_id" => 5,"name" => "Tsibu Darko"],
            ["city_id" => 5,"name" => "Tsimtsimhwe/Kotokuraba"],
            ["city_id" => 5,"name" => "Turom"],
            ["city_id" => 5,"name" => "University New Site"],
            ["city_id" => 5,"name" => "University Old Site"],
            ["city_id" => 5,"name" => "Wakram"],
            ["city_id" => 5,"name" => "Yamoransa"],
            ["city_id" => 6,"name" => "Abesim"],
            ["city_id" => 6,"name" => "Abetifi"],
            ["city_id" => 6,"name" => "Abisu"],
            ["city_id" => 6,"name" => "Abonsua"],
            ["city_id" => 6,"name" => "Abosa"],
            ["city_id" => 6,"name" => "Abronye"],
            ["city_id" => 6,"name" => "Adamstown"],
            ["city_id" => 6,"name" => "Adantia"],
            ["city_id" => 6,"name" => "Addoe"],
            ["city_id" => 6,"name" => "Aduonya"],
            ["city_id" => 6,"name" => "Agyinasie"],
            ["city_id" => 6,"name" => "Ahenboboano"],
            ["city_id" => 6,"name" => "Ahenfie"],
            ["city_id" => 6,"name" => "Airport"],
            ["city_id" => 6,"name" => "Akokorakwadwo"],
            ["city_id" => 6,"name" => "Akuoko"],
            ["city_id" => 6,"name" => "Akyeremanyaa"],
            ["city_id" => 6,"name" => "Anhwere"],
            ["city_id" => 6,"name" => "Ankobea"],
            ["city_id" => 6,"name" => "Antepim"],
            ["city_id" => 6,"name" => "Antwikrom"],
            ["city_id" => 6,"name" => "Anyinasie"],
            ["city_id" => 6,"name" => "Asabia"],
            ["city_id" => 6,"name" => "Asiapre"],
            ["city_id" => 6,"name" => "Asuakwaa"],
            ["city_id" => 6,"name" => "Asufufu"],
            ["city_id" => 6,"name" => "Atoase"],
            ["city_id" => 6,"name" => "Atronie"],
            ["city_id" => 6,"name" => "Atuahenekrom"],
            ["city_id" => 6,"name" => "Awua"],
            ["city_id" => 6,"name" => "Baakoniaba"],
            ["city_id" => 6,"name" => "Banu-Nkwanta"],
            ["city_id" => 6,"name" => "Berlin Top"],
            ["city_id" => 6,"name" => "Biakoniaba"],
            ["city_id" => 6,"name" => "Boffourkrom"],
            ["city_id" => 6,"name" => "Bofrease"],
            ["city_id" => 6,"name" => "Canada"],
            ["city_id" => 6,"name" => "Central Business District"],
            ["city_id" => 6,"name" => "Cocoa Village"],
            ["city_id" => 6,"name" => "Dominase"],
            ["city_id" => 6,"name" => "Dormaa"],
            ["city_id" => 6,"name" => "Dumasua"],
            ["city_id" => 6,"name" => "Educational Zone"],
            ["city_id" => 6,"name" => "Fiapre"],
            ["city_id" => 6,"name" => "Fiema"],
            ["city_id" => 6,"name" => "Foase"],
            ["city_id" => 6,"name" => "Gubre"],
            ["city_id" => 6,"name" => "Gyaase"],
            ["city_id" => 6,"name" => "Koduakrom"],
            ["city_id" => 6,"name" => "Kotokrom"],
            ["city_id" => 6,"name" => "Kwatire"],
            ["city_id" => 6,"name" => "Kwatwema"],
            ["city_id" => 6,"name" => "Kyeremeh"],
            ["city_id" => 6,"name" => "Lowcost"],
            ["city_id" => 6,"name" => "Magazine"],
            ["city_id" => 6,"name" => "Mantukwa"],
            ["city_id" => 6,"name" => "Mireku"],
            ["city_id" => 6,"name" => "Nana Bosoma Market"],
            ["city_id" => 6,"name" => "New Dormaa"],
            ["city_id" => 6,"name" => "New Dormaa East"],
            ["city_id" => 6,"name" => "New Town"],
            ["city_id" => 6,"name" => "Nkranketewa"],
            ["city_id" => 6,"name" => "Nkrankrom"],
            ["city_id" => 6,"name" => "Nkwabeng"],
            ["city_id" => 6,"name" => "Nsansama"],
            ["city_id" => 6,"name" => "Nsesreso"],
            ["city_id" => 6,"name" => "Nwawasua"],
            ["city_id" => 6,"name" => "OK/Estate"],
            ["city_id" => 6,"name" => "Oyoko"],
            ["city_id" => 6,"name" => "Penkwase"],
            ["city_id" => 6,"name" => "Sunyani Airport"],
            ["city_id" => 6,"name" => "Sunyanitifi"],
            ["city_id" => 6,"name" => "Tainso"],
            ["city_id" => 6,"name" => "Tanoakyi"],
            ["city_id" => 6,"name" => "Tonsuom"],
            ["city_id" => 6,"name" => "Tumiamienko"],
            ["city_id" => 6,"name" => "Twumasikrom"],
            ["city_id" => 6,"name" => "Watchman"],
            ["city_id" => 6,"name" => "Yawhima"],
            ["city_id" => 6,"name" => "Yawhimakrom"],
            ["city_id" => 6,"name" => "Yawsae"],
            ["city_id" => 6,"name" => "Yentreso"],
            ["city_id" => 6,"name" => "Zongo"],
            ["city_id" => 6,"name" => "Zongo New Town"],
            ["city_id" => 7,"name" => "Agric Devt Bank"],
            ["city_id" => 7,"name" => "Assemblies Of God"],
            ["city_id" => 7,"name" => "Bangyili"],
            ["city_id" => 7,"name" => "Banvim"],
            ["city_id" => 7,"name" => "Batanyili"],
            ["city_id" => 7,"name" => "Bawa Barracks"],
            ["city_id" => 7,"name" => "Bawah Barracks"],
            ["city_id" => 7,"name" => "Bilpella"],
            ["city_id" => 7,"name" => "Bogkurugu"],
            ["city_id" => 7,"name" => "Buglangfong"],
            ["city_id" => 7,"name" => "Bukpomo"],
            ["city_id" => 7,"name" => "Central Business District"],
            ["city_id" => 7,"name" => "Central Market"],
            ["city_id" => 7,"name" => "Chaanshegu"],
            ["city_id" => 7,"name" => "Changnaayili"],
            ["city_id" => 7,"name" => "Changni"],
            ["city_id" => 7,"name" => "Checko"],
            ["city_id" => 7,"name" => "Cheshei"],
            ["city_id" => 7,"name" => "Choggu Mmanaayili"],
            ["city_id" => 7,"name" => "Choggu West"],
            ["city_id" => 7,"name" => "Chogo-manayili"],
            ["city_id" => 7,"name" => "Chogu"],
            ["city_id" => 7,"name" => "Chogu-Yapalsi"],
            ["city_id" => 7,"name" => "Dabokpa"],
            ["city_id" => 7,"name" => "Dakpemah"],
            ["city_id" => 7,"name" => "Dalinbla"],
            ["city_id" => 7,"name" => "Dalogyili"],
            ["city_id" => 7,"name" => "Damankunyili"],
            ["city_id" => 7,"name" => "Damankunyili"],
            ["city_id" => 7,"name" => "Datoyili"],
            ["city_id" => 7,"name" => "Dimala"],
            ["city_id" => 7,"name" => "Doboagshie"],
            ["city_id" => 7,"name" => "Dohinayili"],
            ["city_id" => 7,"name" => "Dohinni"],
            ["city_id" => 7,"name" => "Dufaa"],
            ["city_id" => 7,"name" => "Dugshegu"],
            ["city_id" => 7,"name" => "Dungu"],
            ["city_id" => 7,"name" => "Dungu-Asawaba"],
            ["city_id" => 7,"name" => "Duuyin"],
            ["city_id" => 7,"name" => "Education Ridge"],
            ["city_id" => 7,"name" => "Fooshegu"],
            ["city_id" => 7,"name" => "Fuo"],
            ["city_id" => 7,"name" => "Fuo Village"],
            ["city_id" => 7,"name" => "Futa"],
            ["city_id" => 7,"name" => "Garizee"],
            ["city_id" => 7,"name" => "Gariziegu"],
            ["city_id" => 7,"name" => "Gbabshe"],
            ["city_id" => 7,"name" => "Gbalahi"],
            ["city_id" => 7,"name" => "Gbalo-Kpalsi"],
            ["city_id" => 7,"name" => "Gbanyamli"],
            ["city_id" => 7,"name" => "Gbrimah"],
            ["city_id" => 7,"name" => "Gburima"],
            ["city_id" => 7,"name" => "Gumani"],
            ["city_id" => 7,"name" => "Gumani"],
            ["city_id" => 7,"name" => "Gumbihini"],
            ["city_id" => 7,"name" => "Gunnaayili"],
            ["city_id" => 7,"name" => "Gurugu"],
            ["city_id" => 7,"name" => "Hill Top"],
            ["city_id" => 7,"name" => "Inter Royals"],
            ["city_id" => 7,"name" => "Jakarayili"],
            ["city_id" => 7,"name" => "Jatong-dakpemyili"],
            ["city_id" => 7,"name" => "Jekarayili"],
            ["city_id" => 7,"name" => "Jerigu"],
            ["city_id" => 7,"name" => "Jisonayili"],
            ["city_id" => 7,"name" => "Juni"],
            ["city_id" => 7,"name" => "Kakpagyili"],
            ["city_id" => 7,"name" => "Kalariga"],
            ["city_id" => 7,"name" => "Kalipohin"],
            ["city_id" => 7,"name" => "Kalpohin Estates"],
            ["city_id" => 7,"name" => "Kalpohin Village"],
            ["city_id" => 7,"name" => "Kamina"],
            ["city_id" => 7,"name" => "Kamina Barracks"],
            ["city_id" => 7,"name" => "Kanvilli"],
            ["city_id" => 7,"name" => "Kanvil-tuunaayili"],
            ["city_id" => 7,"name" => "Kasalgu"],
            ["city_id" => 7,"name" => "Katariga"],
            ["city_id" => 7,"name" => "Kobilmahagu"],
            ["city_id" => 7,"name" => "Kogni"],
            ["city_id" => 7,"name" => "Kotingli"],
            ["city_id" => 7,"name" => "Kpalsi"],
            ["city_id" => 7,"name" => "Kpanvo"],
            ["city_id" => 7,"name" => "Kpawomo"],
            ["city_id" => 7,"name" => "Kpawumo"],
            ["city_id" => 7,"name" => "Kpeni"],
            ["city_id" => 7,"name" => "Kpinjinga"],
            ["city_id" => 7,"name" => "Kpuntaliga"],
            ["city_id" => 7,"name" => "Kukuo"],
            ["city_id" => 7,"name" => "Kulaa"],
            ["city_id" => 7,"name" => "Kulnyevila"],
            ["city_id" => 7,"name" => "Kumbuyili"],
            ["city_id" => 7,"name" => "Lahagu"],
            ["city_id" => 7,"name" => "Lamacara"],
            ["city_id" => 7,"name" => "Lamashegu"],
            ["city_id" => 7,"name" => "Malshegu"],
            ["city_id" => 7,"name" => "Manguli"],
            ["city_id" => 7,"name" => "Mohiyibihi"],
            ["city_id" => 7,"name" => "Moshie Zongo"],
            ["city_id" => 7,"name" => "Nachimbaya"],
            ["city_id" => 7,"name" => "Nakpanzoo"],
            ["city_id" => 7,"name" => "Nalung"],
            ["city_id" => 7,"name" => "Namandu"],
            ["city_id" => 7,"name" => "Nangbagu Yipala"],
            ["city_id" => 7,"name" => "Ngarun"],
            ["city_id" => 7,"name" => "Nyanshegu"],
            ["city_id" => 7,"name" => "Nyerizei"],
            ["city_id" => 7,"name" => "Nyeshie"],
            ["city_id" => 7,"name" => "Nyeshie"],
            ["city_id" => 7,"name" => "Nyohini "],
            ["city_id" => 7,"name" => "Pagazaa"],
            ["city_id" => 7,"name" => "Parishei"],
            ["city_id" => 7,"name" => "Russian Bungalows"],
            ["city_id" => 7,"name" => "Sabonjida (Ward H)"],
            ["city_id" => 7,"name" => "Sagnarigu"],
            ["city_id" => 7,"name" => "Sagnarigu-Dungu"],
            ["city_id" => 7,"name" => "Sakasaka"],
            ["city_id" => 7,"name" => "Sakasaka Quarters"],
            ["city_id" => 7,"name" => "Salamba"],
            ["city_id" => 7,"name" => "Sanga"],
            ["city_id" => 7,"name" => "Shigu"],
            ["city_id" => 7,"name" => "Shishegu"],
            ["city_id" => 7,"name" => "Sognaayili"],
            ["city_id" => 7,"name" => "Sognayili"],
            ["city_id" => 7,"name" => "Sorugu"],
            ["city_id" => 7,"name" => "SSNIT Flats"],
            ["city_id" => 7,"name" => "Sugashei"],
            ["city_id" => 7,"name" => "Taha"],
            ["city_id" => 7,"name" => "Tamale Airport"],
            ["city_id" => 7,"name" => "Tampei-Kukuo"],
            ["city_id" => 7,"name" => "Tatale-Obore"],
            ["city_id" => 7,"name" => "Ticheli"],
            ["city_id" => 7,"name" => "Tishegu"],
            ["city_id" => 7,"name" => "Tugu"],
            ["city_id" => 7,"name" => "Tugu"],
            ["city_id" => 7,"name" => "Tuutingli"],
            ["city_id" => 7,"name" => "Victory Cinema"],
            ["city_id" => 7,"name" => "Vitin-dabogse"],
            ["city_id" => 7,"name" => "Vittin"],
            ["city_id" => 7,"name" => "Wamale"],
            ["city_id" => 7,"name" => "Wayamba"],
            ["city_id" => 7,"name" => "Worize"],
            ["city_id" => 7,"name" => "Wovugu"],
            ["city_id" => 7,"name" => "Wulanyili"],
            ["city_id" => 7,"name" => "Yagyili"],
            ["city_id" => 7,"name" => "Yilonayili"],
            ["city_id" => 7,"name" => "Yong"],
            ["city_id" => 7,"name" => "Yong-Dakpemyili"],
            ["city_id" => 7,"name" => "Yongduuni"],
            ["city_id" => 7,"name" => "Zagyuri"],
            ["city_id" => 7,"name" => "Zagyuri"],
            ["city_id" => 7,"name" => "Zakaliyili"],
            ["city_id" => 7,"name" => "Zibogo"],
            ["city_id" => 7,"name" => "Zogbeli"],
            ["city_id" => 7,"name" => "Zujung"],
            ["city_id" => 7,"name" => "Zuo"],
            ["city_id" => 7,"name" => "Zuozugu"],
            ["city_id" => 8,"name" => "Abutia-Agorve"],
            ["city_id" => 8,"name" => "Akoefe Kpenoe"],
            ["city_id" => 8,"name" => "Akome"],
            ["city_id" => 8,"name" => "Akrofu"],
            ["city_id" => 8,"name" => "Amedzofe"],
            ["city_id" => 8,"name" => "Amevor"],
            ["city_id" => 8,"name" => "Anagokordzi"],
            ["city_id" => 8,"name" => "Anfoeta-Tsyome"],
            ["city_id" => 8,"name" => "Anlokordzi"],
            ["city_id" => 8,"name" => "Anyirawase"],
            ["city_id" => 8,"name" => "Atikpui"],
            ["city_id" => 8,"name" => "Avee"],
            ["city_id" => 8,"name" => "Avenui"],
            ["city_id" => 8,"name" => "Awatidome"],
            ["city_id" => 8,"name" => "Awlime Todze"],
            ["city_id" => 8,"name" => "Awuiasu"],
            ["city_id" => 8,"name" => "Bagble"],
            ["city_id" => 8,"name" => "Bake – Gbloefe"],
            ["city_id" => 8,"name" => "Barracks new town"],
            ["city_id" => 8,"name" => "Biakpa"],
            ["city_id" => 8,"name" => "Blisam"],
            ["city_id" => 8,"name" => "Borsontoe"],
            ["city_id" => 8,"name" => "Central Market"],
            ["city_id" => 8,"name" => "Dave"],
            ["city_id" => 8,"name" => "Dededo Kpetornu"],
            ["city_id" => 8,"name" => "Deme"],
            ["city_id" => 8,"name" => "Dodome"],
            ["city_id" => 8,"name" => "Donorkordzi"],
            ["city_id" => 8,"name" => "Duga"],
            ["city_id" => 8,"name" => "Dzolo"],
            ["city_id" => 8,"name" => "Executive Gardens"],
            ["city_id" => 8,"name" => "Fiave"],
            ["city_id" => 8,"name" => "Fume"],
            ["city_id" => 8,"name" => "Gbogame"],
            ["city_id" => 8,"name" => "Godokpoe"],
            ["city_id" => 8,"name" => "Hlefi"],
            ["city_id" => 8,"name" => "Hliha"],
            ["city_id" => 8,"name" => "Ho Ahoe"],
            ["city_id" => 8,"name" => "Ho Airport"],
            ["city_id" => 8,"name" => "Ho Bankoe"],
            ["city_id" => 8,"name" => "Ho Central"],
            ["city_id" => 8,"name" => "Ho Dome"],
            ["city_id" => 8,"name" => "Ho Fiave"],
            ["city_id" => 8,"name" => "Ho Heve"],
            ["city_id" => 8,"name" => "Ho Hliha"],
            ["city_id" => 8,"name" => "Ho Kpevele"],
            ["city_id" => 8,"name" => "Ho Municipal Hospital"],
            ["city_id" => 8,"name" => "Ho Sports Stadium"],
            ["city_id" => 8,"name" => "Ho Teaching Hospital"],
            ["city_id" => 8,"name" => "Ho Technical University"],
            ["city_id" => 8,"name" => "Hodzo"],
            ["city_id" => 8,"name" => "Hoe"],
            ["city_id" => 8,"name" => "Hofedo"],
            ["city_id" => 8,"name" => "Hoƒedo"],
            ["city_id" => 8,"name" => "Holuta"],
            ["city_id" => 8,"name" => "Housing"],
            ["city_id" => 8,"name" => "Kalakpa National Reserve"],
            ["city_id" => 8,"name" => "Klave"],
            ["city_id" => 8,"name" => "Klefe"],
            ["city_id" => 8,"name" => "Kloe"],
            ["city_id" => 8,"name" => "Kpale-Etodome"],
            ["city_id" => 8,"name" => "Kpoeta"],
            ["city_id" => 8,"name" => "Kpota"],
            ["city_id" => 8,"name" => "Little Bethlehem"],
            ["city_id" => 8,"name" => "Loboli"],
            ["city_id" => 8,"name" => "Lokoe"],
            ["city_id" => 8,"name" => "Lume"],
            ["city_id" => 8,"name" => "Matse"],
            ["city_id" => 8,"name" => "Mawuli Estate"],
            ["city_id" => 8,"name" => "Nyive"],
            ["city_id" => 8,"name" => "Powerhouse"],
            ["city_id" => 8,"name" => "Saviefe"],
            ["city_id" => 8,"name" => "Shia "],
            ["city_id" => 8,"name" => "Somey down"],
            ["city_id" => 8,"name" => "Sreme-Anoe"],
            ["city_id" => 8,"name" => "Ssnit Flats"],
            ["city_id" => 8,"name" => "Takla"],
            ["city_id" => 8,"name" => "Tanyigbe"],
            ["city_id" => 8,"name" => "Taviefe"],
            ["city_id" => 8,"name" => "Teti"],
            ["city_id" => 8,"name" => "Tokokoe"],
            ["city_id" => 8,"name" => "Toviadzi"],
            ["city_id" => 8,"name" => "Tsibu-Dafor"],
            ["city_id" => 8,"name" => "Tsito Anyigbe"],
            ["city_id" => 8,"name" => "Tsito Dzigbe"],
            ["city_id" => 8,"name" => "University of Health and Allied Sciences "],
            ["city_id" => 8,"name" => "Vane"],
            ["city_id" => 8,"name" => "Voradep village"],
            ["city_id" => 8,"name" => "Wusu – Dome"],
            ["city_id" => 8,"name" => "Ziavi"],
            ["city_id" => 9,"name" => "Abanim"],
            ["city_id" => 9,"name" => "Abawdikro"],
            ["city_id" => 9,"name" => "Abease"],
            ["city_id" => 9,"name" => "Abease"],
            ["city_id" => 9,"name" => "Abemagya"],
            ["city_id" => 9,"name" => "Abromam"],
            ["city_id" => 9,"name" => "Adantase"],
            ["city_id" => 9,"name" => "Addaekrom"],
            ["city_id" => 9,"name" => "Adutwie"],
            ["city_id" => 9,"name" => "Agosa"],
            ["city_id" => 9,"name" => "Agyina"],
            ["city_id" => 9,"name" => "Ahansua"],
            ["city_id" => 9,"name" => "Ahenbronoso"],
            ["city_id" => 9,"name" => "Ahenfie"],
            ["city_id" => 9,"name" => "Ahenfie"],
            ["city_id" => 9,"name" => "Akisimasu"],
            ["city_id" => 9,"name" => "Akonkonti"],
            ["city_id" => 9,"name" => "Akrofrom"],
            ["city_id" => 9,"name" => "Akrofrom"],
            ["city_id" => 9,"name" => "Akyew"],
            ["city_id" => 9,"name" => "Amangoase"],
            ["city_id" => 9,"name" => "Anyinabrem"],
            ["city_id" => 9,"name" => "Asubrofo"],
            ["city_id" => 9,"name" => "Asueyi"],
            ["city_id" => 9,"name" => "Atrensu"],
            ["city_id" => 9,"name" => "Ayeasu"],
            ["city_id" => 9,"name" => "Baamire"],
            ["city_id" => 9,"name" => "Besedan"],
            ["city_id" => 9,"name" => "Bomire"],
            ["city_id" => 9,"name" => "Bongoroso"],
            ["city_id" => 9,"name" => "Bonkwae"],
            ["city_id" => 9,"name" => "Bonya"],
            ["city_id" => 9,"name" => "Booyem"],
            ["city_id" => 9,"name" => "Dagombaline"],
            ["city_id" => 9,"name" => "Dampaso"],
            ["city_id" => 9,"name" => "Denteso"],
            ["city_id" => 9,"name" => "Dompoase"],
            ["city_id" => 9,"name" => "Dwomor"],
            ["city_id" => 9,"name" => "Ebomso"],
            ["city_id" => 9,"name" => "Fiaso"],
            ["city_id" => 9,"name" => "Forikrom"],
            ["city_id" => 9,"name" => "Forikrom"],
            ["city_id" => 9,"name" => "Gyaase"],
            ["city_id" => 9,"name" => "Hansua"],
            ["city_id" => 9,"name" => "Hausaline"],
            ["city_id" => 9,"name" => "Jama-Temponim"],
            ["city_id" => 9,"name" => "Kenten"],
            ["city_id" => 9,"name" => "Kofoso"],
            ["city_id" => 9,"name" => "Konimase"],
            ["city_id" => 9,"name" => "Kuntunso"],
            ["city_id" => 9,"name" => "Mesidan"],
            ["city_id" => 9,"name" => "Nana Atti"],
            ["city_id" => 9,"name" => "New Dwomor"],
            ["city_id" => 9,"name" => "New Tunsuase"],
            ["city_id" => 9,"name" => "Nkrankrom"],
            ["city_id" => 9,"name" => "Nsuta"],
            ["city_id" => 9,"name" => "Ntoase"],
            ["city_id" => 9,"name" => "Ntoase"],
            ["city_id" => 9,"name" => "Ofuman"],
            ["city_id" => 9,"name" => "Sansama"],
            ["city_id" => 9,"name" => "Sansua"],
            ["city_id" => 9,"name" => "Subingya"],
            ["city_id" => 9,"name" => "Tachiman Market"],
            ["city_id" => 9,"name" => "Tadeeso"],
            ["city_id" => 9,"name" => "Takofiano"],
            ["city_id" => 9,"name" => "Takofiano"],
            ["city_id" => 9,"name" => "Tanoboase"],
            ["city_id" => 9,"name" => "Tanoboase"],
            ["city_id" => 9,"name" => "Tentenano/Nkruwaso"],
            ["city_id" => 9,"name" => "Tunsuase"],
            ["city_id" => 9,"name" => "Tuobodom"],
            ["city_id" => 9,"name" => "Tuobodom"],
            ["city_id" => 9,"name" => "Twimia Koase"],
            ["city_id" => 9,"name" => "Twimia-Nkwanta"],
            ["city_id" => 9,"name" => "Wangara Line"],
            ["city_id" => 9,"name" => "Zongo"],
            ["city_id" => 10,"name" => "Goaso Ahenboboano :"],
            ["city_id" => 10,"name" => "Goaso Market"],
            ["city_id" => 10,"name" => "Manhyia"],
            ["city_id" => 10,"name" => "Nursing and Midwifery Training College"],
            ["city_id" => 11,"name" => "Abrodua"],
            ["city_id" => 11,"name" => "Ada"],
            ["city_id" => 11,"name" => "Adaneagya"],
            ["city_id" => 11,"name" => "Adontua"],
            ["city_id" => 11,"name" => "Adumasa"],
            ["city_id" => 11,"name" => "Adweso Estates"],
            ["city_id" => 11,"name" => "Adweso Town"],
            ["city_id" => 11,"name" => "Ahenbronom Jumapo"],
            ["city_id" => 11,"name" => "Akwaasu Asebi"],
            ["city_id" => 11,"name" => "Akwadum"],
            ["city_id" => 11,"name" => "All Nations University"],
            ["city_id" => 11,"name" => "Anglican"],
            ["city_id" => 11,"name" => "Anlo Town North"],
            ["city_id" => 11,"name" => "Anlo Town South"],
            ["city_id" => 11,"name" => "Asamang"],
            ["city_id" => 11,"name" => "Asikasu"],
            ["city_id" => 11,"name" => "Asokore"],
            ["city_id" => 11,"name" => "Asokore Ntano"],
            ["city_id" => 11,"name" => "Asuofiriso"],
            ["city_id" => 11,"name" => "Asuogya"],
            ["city_id" => 11,"name" => "Betom"],
            ["city_id" => 11,"name" => "Central Business District"],
            ["city_id" => 11,"name" => "Central Hospital"],
            ["city_id" => 11,"name" => "Central Market"],
            ["city_id" => 11,"name" => "Community A "],
            ["city_id" => 11,"name" => "Community B"],
            ["city_id" => 11,"name" => "Community C"],
            ["city_id" => 11,"name" => "Community D"],
            ["city_id" => 11,"name" => "Damang"],
            ["city_id" => 11,"name" => "Dansuagya"],
            ["city_id" => 11,"name" => "Debrakrom"],
            ["city_id" => 11,"name" => "Dwumapo"],
            ["city_id" => 11,"name" => "Eddi Mensah"],
            ["city_id" => 11,"name" => "Effiduase"],
            ["city_id" => 11,"name" => "Effiduase Market"],
            ["city_id" => 11,"name" => "Fofie"],
            ["city_id" => 11,"name" => "Gyamfikrom"],
            ["city_id" => 11,"name" => "Jumapo"],
            ["city_id" => 11,"name" => "Kantudu"],
            ["city_id" => 11,"name" => "Klu Town"],
            ["city_id" => 11,"name" => "Koforidua Principal Street"],
            ["city_id" => 11,"name" => "Koforidua Tehnical University"],
            ["city_id" => 11,"name" => "Nsukwaoso"],
            ["city_id" => 11,"name" => "Nsukwaoso Abotanso"],
            ["city_id" => 11,"name" => "Nyamekrom"],
            ["city_id" => 11,"name" => "Nyerede North"],
            ["city_id" => 11,"name" => "Nyerede South"],
            ["city_id" => 11,"name" => "Oguaa"],
            ["city_id" => 11,"name" => "Oguaa"],
            ["city_id" => 11,"name" => "Ohemaa Park"],
            ["city_id" => 11,"name" => "Okorase"],
            ["city_id" => 11,"name" => "Old Estate East"],
            ["city_id" => 11,"name" => "Old Estate West"],
            ["city_id" => 11,"name" => "Osabene Mile 50"],
            ["city_id" => 11,"name" => "Oyoko"],
            ["city_id" => 11,"name" => "Oyoko Zongo"],
            ["city_id" => 11,"name" => "Railway Station"],
            ["city_id" => 11,"name" => "Residential Area"],
            ["city_id" => 11,"name" => "School Town"],
            ["city_id" => 11,"name" => "Sempoamiensa"],
            ["city_id" => 11,"name" => "Social Welfare"],
            ["city_id" => 11,"name" => "Srodae"],
            ["city_id" => 11,"name" => "Suhyen"],
            ["city_id" => 11,"name" => "Sukumu Effiduase"],
            ["city_id" => 11,"name" => "Sukuumu"],
            ["city_id" => 11,"name" => "Tanoso"],
            ["city_id" => 11,"name" => "Two Streams"],
            ["city_id" => 11,"name" => "Yaane"],
            ["city_id" => 11,"name" => "Zongo"],
            ["city_id" => 11,"name" => "Zongo Market"],
            ["city_id" => 12,"name" => "Achubunyo"],
            ["city_id" => 12,"name" => "Alhassan Kura"],
            ["city_id" => 12,"name" => "Apilso"],
            ["city_id" => 12,"name" => "Attributo"],
            ["city_id" => 12,"name" => "Busunu"],
            ["city_id" => 12,"name" => "Canteen"],
            ["city_id" => 12,"name" => "Damongo Principal Street"],
            ["city_id" => 12,"name" => "Damongo Market"],
            ["city_id" => 12,"name" => "Dass"],
            ["city_id" => 12,"name" => "Frafra Settlement 1"],
            ["city_id" => 12,"name" => "Frafra Settlement 6"],
            ["city_id" => 12,"name" => "Hangaline"],
            ["city_id" => 12,"name" => "Kojokura"],
            ["city_id" => 12,"name" => "Langbanto"],
            ["city_id" => 12,"name" => "Laribanga"],
            ["city_id" => 12,"name" => "Mole Game"],
            ["city_id" => 12,"name" => "Nabori"],
            ["city_id" => 12,"name" => "Sori"],
            ["city_id" => 12,"name" => "Yagbon"],
            ["city_id" => 12,"name" => "Yipala"],
            ["city_id" => 12,"name" => "Zongo"],
            ["city_id" => 13,"name" => "Barinya"],
            ["city_id" => 13,"name" => "Bongbini"],
            ["city_id" => 13,"name" => "Bowku"],
            ["city_id" => 13,"name" => "Central Market"],
            ["city_id" => 13,"name" => "Dagbiriboari"],
            ["city_id" => 13,"name" => "Dindani"],
            ["city_id" => 13,"name" => "Dundafong"],
            ["city_id" => 13,"name" => "Gambaranfong"],
            ["city_id" => 13,"name" => "Gbanda"],
            ["city_id" => 13,"name" => "Gbangu"],
            ["city_id" => 13,"name" => "Gbintiri"],
            ["city_id" => 13,"name" => "Gurugu"],
            ["city_id" => 13,"name" => "Jagog"],
            ["city_id" => 13,"name" => "Jawani"],
            ["city_id" => 13,"name" => "Kasape"],
            ["city_id" => 13,"name" => "Kolinvai"],
            ["city_id" => 13,"name" => "Kpakpirigbangu"],
            ["city_id" => 13,"name" => "Kulgona"],
            ["city_id" => 13,"name" => "Langbinsi"],
            ["city_id" => 13,"name" => "Limanfong"],
            ["city_id" => 13,"name" => "Limu"],
            ["city_id" => 13,"name" => "Nagboo"],
            ["city_id" => 13,"name" => "Nakosigufong"],
            ["city_id" => 13,"name" => "Namangu"],
            ["city_id" => 13,"name" => "Namenboku"],
            ["city_id" => 13,"name" => "Nanori"],
            ["city_id" => 13,"name" => "Nayirifong"],
            ["city_id" => 13,"name" => "Sakogu"],
            ["city_id" => 13,"name" => "Samni"],
            ["city_id" => 13,"name" => "Sibiefong"],
            ["city_id" => 13,"name" => "Tuni"],
            ["city_id" => 13,"name" => "Wundua"],
            ["city_id" => 13,"name" => "Yankazia"],
            ["city_id" => 13,"name" => "Za-Ari"],
            ["city_id" => 13,"name" => "Zagrifong"],
            ["city_id" => 13,"name" => "Zambuligu"],
            ["city_id" => 13,"name" => "Zandua"],
            ["city_id" => 14,"name" => "Amogrebisi"],
            ["city_id" => 14,"name" => "Atulbabisi Central"],
            ["city_id" => 14,"name" => "Azorebisi"],
            ["city_id" => 14,"name" => "Basengo"],
            ["city_id" => 14,"name" => "Boligo"],
            ["city_id" => 14,"name" => "Bukere"],
            ["city_id" => 14,"name" => "Central Market"],
            ["city_id" => 14,"name" => "Damweo"],
            ["city_id" => 14,"name" => "Dapoore-Tindongo West"],
            ["city_id" => 14,"name" => "Dorongo"],
            ["city_id" => 14,"name" => "Gumbisi Zongo"],
            ["city_id" => 14,"name" => "Kalbeo"],
            ["city_id" => 14,"name" => "Kolbia"],
            ["city_id" => 14,"name" => "Kolgu/Agusi"],
            ["city_id" => 14,"name" => "Kotokoli-Zongo"],
            ["city_id" => 14,"name" => "Kumbangre"],
            ["city_id" => 14,"name" => "Kumblingo"],
            ["city_id" => 14,"name" => "Lagos-Town"],
            ["city_id" => 14,"name" => "Nyariga"],
            ["city_id" => 14,"name" => "Sabon-Zongo"],
            ["city_id" => 14,"name" => "Soe"],
            ["city_id" => 14,"name" => "Soe Yipaala"],
            ["city_id" => 14,"name" => "Tanzui-Zobisi"],
            ["city_id" => 14,"name" => "Tindonmolgo"],
            ["city_id" => 14,"name" => "Tindonsheo"],
            ["city_id" => 14,"name" => "Tindonsobligo"],
            ["city_id" => 14,"name" => "Yikene"],
            ["city_id" => 14,"name" => "Yorogo"],
            ["city_id" => 14,"name" => "Yorogo Tengre"],
            ["city_id" => 14,"name" => "Zaare East"],
            ["city_id" => 14,"name" => "Zaare West"],
            ["city_id" => 15,"name" => "Bamahu"],
            ["city_id" => 15,"name" => "Boli"],
            ["city_id" => 15,"name" => "Busa"],
            ["city_id" => 15,"name" => "Central Market"],
            ["city_id" => 15,"name" => "Charia"],
            ["city_id" => 15,"name" => "Community Centre"],
            ["city_id" => 15,"name" => "Dandafuro"],
            ["city_id" => 15,"name" => "Degu (Gov't Residential)"],
            ["city_id" => 15,"name" => "Dobile"],
            ["city_id" => 15,"name" => "Dokpong"],
            ["city_id" => 15,"name" => "Dondoli"],
            ["city_id" => 15,"name" => "Fifamuni"],
            ["city_id" => 15,"name" => "Fongu"],
            ["city_id" => 15,"name" => "Guli"],
            ["city_id" => 15,"name" => "Jingu"],
            ["city_id" => 15,"name" => "Jonga"],
            ["city_id" => 15,"name" => "Kabanye"],
            ["city_id" => 15,"name" => "Kambali"],
            ["city_id" => 15,"name" => "Kpaguri"],
            ["city_id" => 15,"name" => "Kperisi"],
            ["city_id" => 15,"name" => "Kpongu"],
            ["city_id" => 15,"name" => "Kumbiahi"],
            ["city_id" => 15,"name" => "Kunta"],
            ["city_id" => 15,"name" => "Limanyiri"],
            ["city_id" => 15,"name" => "Mangu"],
            ["city_id" => 15,"name" => "Nakori"],
            ["city_id" => 15,"name" => "Nayiri"],
            ["city_id" => 15,"name" => "Sing"],
            ["city_id" => 15,"name" => "Sokpayiri"],
            ["city_id" => 15,"name" => "Sombo"],
            ["city_id" => 15,"name" => "Tagirayiri"],
            ["city_id" => 15,"name" => "Yibile"],
            ["city_id" => 15,"name" => "Zongo"],
            ["city_id" => 16,"name" => "Banka"],
            ["city_id" => 16,"name" => "Central Market"],
            ["city_id" => 16,"name" => "Chamba Akura"],
            ["city_id" => 16,"name" => "Dambai Central"],
            ["city_id" => 16,"name" => "Dambai Lakeside"],
            ["city_id" => 16,"name" => "Dambai Zongo"],
            ["city_id" => 17,"name" => "Aboagyekrom"],
            ["city_id" => 17,"name" => "Aboanidua"],
            ["city_id" => 17,"name" => "Abourtem"],
            ["city_id" => 17,"name" => "Abrabra"],
            ["city_id" => 17,"name" => "Ahokwa"],
            ["city_id" => 17,"name" => "Amafie"],
            ["city_id" => 17,"name" => "Anhwiaa"],
            ["city_id" => 17,"name" => "Anhwiam"],
            ["city_id" => 17,"name" => "Anyinabrim"],
            ["city_id" => 17,"name" => "Asafo North"],
            ["city_id" => 17,"name" => "Asafo South"],
            ["city_id" => 17,"name" => "Asamang"],
            ["city_id" => 17,"name" => "Asuagya"],
            ["city_id" => 17,"name" => "Buako North"],
            ["city_id" => 17,"name" => "Buako South"],
            ["city_id" => 17,"name" => "Camp"],
            ["city_id" => 17,"name" => "Datano"],
            ["city_id" => 17,"name" => "Dwinase"],
            ["city_id" => 17,"name" => "Ewiase"],
            ["city_id" => 17,"name" => "Keteboy"],
            ["city_id" => 17,"name" => "Kojina"],
            ["city_id" => 17,"name" => "Market Area"],
            ["city_id" => 17,"name" => "New Town"],
            ["city_id" => 17,"name" => "Nsuonsua"],
            ["city_id" => 17,"name" => "Paboase"],
            ["city_id" => 17,"name" => "Punikrom"],
            ["city_id" => 17,"name" => "Sefwi Line"],
            ["city_id" => 17,"name" => "Sui"],
            ["city_id" => 17,"name" => "Suiano"],
            ["city_id" => 17,"name" => "Susumenette"],
            ["city_id" => 17,"name" => "Tanoso"]
        ];

        \Illuminate\Support\Facades\DB::table('towns')->insert($towns);
    }
}
